export const DISCORD_COMMUNITY_EVENTS_QUEUE = 'DISCORD_COMMUNITY_EVENTS_QUEUE';
export const DISCORD_COMMUNITY_EVENTS_START_JOB = 'DISCORD_COMMUNITY_EVENTS_START_JOB';
export const DISCORD_COMMUNITY_EVENTS_END_JOB = 'DISCORD_COMMUNITY_EVENTS_END_JOB';
