export const DISCORD_COMMUNITY_EVENTS_QUEUE = 'DISCORD_COMMUNITY_EVENTS_QUEUE' as const;
export const DISCORD_COMMUNITY_EVENTS_START_JOB = 'DISCORD_COMMUNITY_EVENTS_START_JOB' as const;
export const DISCORD_COMMUNITY_EVENTS_END_JOB = 'DISCORD_COMMUNITY_EVENTS_END_JOB' as const;
