export const AUTH_USER_REPOSITORY = 'AUTH_USER_REPOSITORY' as const;
export const AUTH_ACCOUNT_REPOSITORY = 'AUTH_ACCOUNT_REPOSITORY' as const;
export const AUTH_TOKEN_REPOSITORY = 'AUTH_TOKEN_REPOSITORY' as const;

export const COMMUNITY_EVENT_REPOSITORY = 'COMMUNITY_EVENT_REPOSITORY' as const;
export const COMMUNITY_EVENT_DISCORD_REPOSITORY = 'COMMUNITY_EVENT_DISCORD_REPOSITORY' as const;
export const COMMUNITY_EVENT_PARTICIPANTS_DISCORD_REPOSITORY = 'COMMUNITY_EVENT_PARTICIPANTS_DISCORD_REPOSITORY' as const;

export const DISCORD_GUILD_BOT_SETTINGS_REPOSITORY = 'DISCORD_GUILD_BOT_SETTINGS_REPOSITORY' as const;
export const DISCORD_GUILD_REPOSITORY = 'DISCORD_GUILD_REPOSITORY' as const;
export const DISCORD_USER_REPOSITORY = 'DISCORD_USER_REPOSITORY' as const;

export const POAP_CLAIMS_REPOSITORY = 'POAP_CLAIMS_REPOSITORY' as const;
