#file: noinspection YAMLSchemaValidation
name: Create PR for dev
on:
  push:
    branches:
      - dev
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: pnpm standard-version --dry-run -p > changes.md | exit 0
      - run: node -e "require('./dist/index.js')['parseChangesFile']();"
      - run: gh pr edit -F release.md | exit 0
      - run: gh pr create --base release/dev -F release.md --title "deploy dev -> release/dev" | exit 0
