#file: noinspection YAMLSchemaValidation
name: Create PR for dev
on:
  push:
    branches:
      - dev

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  prepare-versions:
    outputs:
      pnpm_version: ${{ steps.pnpm-version.outputs.prop }}
      node_version: ${{ steps.node-version.outputs.prop }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Node Version
        id: node-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.node'
      - name: Retrieve PNPM Version
        id: pnpm-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.pnpm'
  build-and-test:
    needs: prepare-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.prepare-versions.outputs.node_version }}
      - run: npm install -g pnpm@${{ needs.prepare-versions.outputs.pnpm_version }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
  create-pr:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: gh pr close release/dev | exit 0
      - run: gh pr create --base release/dev --fill --title "dev -> release/dev" | exit 0

