#file: noinspection YAMLSchemaValidation
name: Publish NPM QA Package
on:
  push:
    branches:
      - release/dev
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  prepare-versions-qa:
    outputs:
      pnpm: ${{ steps.pnpm-version.outputs.prop }}
      node: ${{ steps.node-version.outputs.prop }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Node Version
        id: node-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.node'
      - name: Retrieve PNPM Version
        id: pnpm-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'engines.pnpm'
  publish-npm-qa:
    needs: prepare-versions-qa
    environment:
      name: staging
      url: "https://www.npmjs.com/package/@solidchain/badge-buddy-common/v/${{ steps.package-version.outputs.prop }}"
    outputs:
      package: ${{ steps.package-version.outputs.prop }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.prepare-versions-qa.outputs.node }}
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: npm install -g pnpm@${{ needs.prepare-versions-qa.outputs.pnpm }}
      - run: pnpm install
      - run: pnpm test
      - run: npx standard-version --prerelease
      - name: Retrieve Package Version
        id: package-version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
      - run: git push --follow-tags
      - run: pnpm build
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: 'public'
          tag: 'next'
      - uses: vimtor/action-zip@v1
        with:
          files: dist/ CHANGELOG.md LICENSE.md README.md package.json
          dest: dist.zip
      - run: gh release create --generate-notes -p --verify-tag v${{ steps.package-version.outputs.prop }} dist.zip
  create-pr:
    needs: publish-npm-qa
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch
      - run: git pull --tags
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: gh pr close release/dev | exit 0
      - run: gh pr create --base main --fill --title "deploy v${{ needs.publish-npm-qa.outputs.package }} to production"
      - run: git checkout dev
      - run: git merge --no-ff release/dev -m "sync branch release/dev v${{ needs.publish-npm-qa.outputs.package }} into dev" | exit 0
      - run: git push

