#file: noinspection YAMLSchemaValidation
name: Publish NPM QA Package
on:
    push:
        branches:
        - dev
jobs:
    prepare-versions:
      outputs:
        pnpm_version: ${{ steps.pnpm-version.outputs.prop }}
        node_version: ${{ steps.node-version.outputs.prop }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Retrieve Node Version
          id: node-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.node'
        - name: Retrieve PNPM Version
          id: pnpm-version
          uses: notiz-dev/github-action-json-property@v0.2.0
          with:
            path: 'package.json'
            prop_path: 'engines.pnpm'
    publish-npm:
      needs: prepare-versions
      outputs:
        environment_url: "https://www.npmjs.com/package/@solidchain/badge-buddy-common/v/${{ steps.package-version.outputs.prop }}"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ needs.prepare-versions.outputs.node_version }}
        - run: |
            git config --global user.name "Github Actions"
            git config --global user.email "patinobrian@gmail.com"
            npm install -g pnpm@${{ needs.prepare-versions.outputs.pnpm_version }}
            pnpm install
            pnpm release -p
            git push --follow-tags
            pnpm build
        - uses: JS-DevTools/npm-publish@v2
          with:
            token: ${{ secrets.NPM_PUBLISH_TOKEN }}
            access: 'public'
            tag: 'next'
